import type { NextPage } from "next";
import Head from "next/head";

const Profile: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>You are logged in</h1>
    </div>
  );
};

export default Profile;
