import { Button, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import sessionCheck from "../lib/session-check";
import { useSession } from "next-auth/react";
import logout from "../lib/logout";

const Profile: NextPage = () => {
  useEffect(() => {
    sessionCheck();
  }, []);

  const { data } = useSession();
  const user = data?.user;

  const [logoutLoading, setLogoutLoading] = useState(false);

  return (
    <div className="container mx-auto p-4">
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Welcome, {user?.display_name || user?.email}</Heading>
      <Button
        colorScheme="red"
        onClick={() => {
          setLogoutLoading(true);
          logout();
        }}
        mt={4}
        isLoading={logoutLoading}
        loadingText="Logging out..."
      >
        Logout
      </Button>
    </div>
  );
};

export default Profile;
