import { Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import sessionCheck from "../lib/session-check";
import { useSession } from "next-auth/react";

const Profile: NextPage = () => {
  useEffect(() => {
    sessionCheck();
  }, []);

  const { data } = useSession();
  const user = data?.user;

  return (
    <div className="container mx-auto p-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>Welcome, {user?.display_name || user?.email}</Heading>
    </div>
  );
};

export default Profile;
