import type { NextPage } from "next";
import Head from "next/head";
import { Heading } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Heading>Lorem ipsum</Heading>
      </div>
    </div>
  );
};

export default Home;
