import type { NextPage } from "next";
import Head from "next/head";
import {
  FormControl,
  FormLabel,
  Input,
  Button,
  useToast,
} from "@chakra-ui/react";
import { Field, Form, Formik, FormikValues } from "formik";
import axios from "../lib/axios";
import Cookies from "js-cookie";
import { getSession, signIn } from "next-auth/react";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Login: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    const key = Cookies.get("key");
    if (key) router.push("/account");
  }, [router]);

  const toast = useToast();

  const onSubmit = async (data: FormikValues) => {
    await signIn("credentials", {
      redirect: false,
      email: data.email,
      password: data.password,
    }).then(async (response) => {
      const session = await getSession();

      if (response?.ok && session?.user?.key) {
        Cookies.set("key", session?.user?.key, {
          expires: 1,
        });
        axios.defaults.headers.common[
          "Authorization"
        ] = `Token ${session?.user?.key}`;

        toast({
          title: "Login Berhasil",
          status: "success",
        });

        router.push("/account");
      }

      if (response?.status === 401) {
        toast({
          title: "Login Gagal",
          description: "Email atau password salah",
          status: "error",
        });
      }
    });
  };

  return (
    <div className="container mx-auto p-4">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-xl mx-auto flex h-full justify-center items-center mt-24">
        <div className="flex flex-col gap-4 w-full">
          <h1 className="text-2xl font-bold">Masuk</h1>
          <Formik
            initialValues={{ email: "", password: "" }}
            onSubmit={onSubmit}
          >
            {() => (
              <Form>
                <Field name="email">
                  {({ field }: any) => (
                    <FormControl mt={4}>
                      <FormLabel>Email</FormLabel>
                      <Input
                        {...field}
                        type="email"
                        placeholder="Masukkan email"
                      />
                    </FormControl>
                  )}
                </Field>
                <Field name="password">
                  {({ field }: any) => (
                    <FormControl mt={4}>
                      <FormLabel>Password</FormLabel>
                      <Input
                        {...field}
                        placeholder="Masukkan password"
                        type="password"
                      />
                    </FormControl>
                  )}
                </Field>
                <Button
                  mt={4}
                  colorScheme="teal"
                  isLoading={false}
                  type="submit"
                >
                  Login
                </Button>
              </Form>
            )}
          </Formik>
        </div>
      </div>
    </div>
  );
};

export default Login;
